apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: app
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: abhishekf5/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: app
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

