apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: app
  labels:
    app: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: erhardikfreelancer/django-todoapp:1.0.0
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: app
spec:
  selector:
    app: todos
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

